version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    ports:
      - "3307:3306" # Puerto local:puerto del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: admin_password  # Contraseña del usuario root
      MYSQL_DATABASE: gestiondb  # Nombre de la base de datos inicial
      MYSQL_USER: admin_user  # Usuario adicional
      MYSQL_PASSWORD: admin_password  # Contraseña del usuario adicional
    volumes:
      - mysql_data:/var/lib/mysql # Volumen persistente para los datos

volumes:
  mysql_data:
    driver: local
